# Generated by Django 4.1.1 on 2023-02-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='dish-pictures'),
        ),
        migrations.AlterField(
            model_name='dishstep',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='dishstep-pictures'),
        ),
    ]
