# Generated by Django 4.1.1 on 2023-02-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dish_picture_alter_dishstep_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsedTag',
        ),
    ]
