# Generated by Django 4.1.1 on 2023-02-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_usedtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='recommended',
            field=models.BooleanField(default=False, verbose_name='В рекомендациях'),
        ),
    ]
