# Generated by Django 4.1.1 on 2023-02-17 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_dish_options_alter_dishproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='api.tag', verbose_name='Тэги'),
        ),
    ]
