# Generated by Django 4.1.1 on 2023-03-16 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userlikeddish_delete_userdish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlikeddish',
            options={'verbose_name': 'Понравившиеся пользователю блюдо', 'verbose_name_plural': 'Понравившиеся пользователю блюда'},
        ),
        migrations.AlterUniqueTogether(
            name='userlikeddish',
            unique_together={('dish', 'user')},
        ),
    ]
